module.exports = {
    //Bill
    CREATE_BILL: 'CREATE_BILL',
    UPDATE_BILL: 'UPDATE_BILL',
    DELETE_BILL: 'DELETE_BILL',
    
    //Category
    CREATE_CATEGORY: 'CREATE_CATEGORY',
    UPDATE_CATEGORY: 'UPDATE_CATEGORY',
    DELETE_CATEGORY: 'DELETE_CATEGORY',
    
    //Calendar
    CREATE_CALENDER: 'CREATE_CALENDER',
    UPDATE_CALENDER: 'UPDATE_CALENDER',
    DELETE_CALENDER: 'DELETE_CALENDER',
    
    //Merchandise
    CREATE_MERCHANDISE: 'CREATE_MERCHANDISE',
    UPDATE_MERCHANDISE: 'UPDATE_MERCHANDISE',
    DELETE_MERCHANDISE: 'DELETE_MERCHANDISE',
    
    //Store
    CREATE_STORE: 'CREATE_STORE',
    UPDATE_STORE: 'UPDATE_STORE',
    DELETE_STORE: 'DELETE_STORE',
    
    //Warehouse
    CREATE_WAREHOUSE: 'CREATE_WAREHOUSE',
    UPDATE_WAREHOUSE: 'UPDATE_WAREHOUSE',
    DELETE_WAREHOUSE: 'DELETE_WAREHOUSE',
    
    //Supplier
    CREATE_SUPPLIER: 'CREATE_SUPPLIER',
    UPDATE_SUPPLIER: 'UPDATE_SUPPLIER',
    DELETE_SUPPLIER: 'DELETE_SUPPLIER',

    //User
    CREATE_USER: 'CREATE_USER',
    UPDATE_USER: 'UPDATE_USER',
    DELETE_USER: 'DELETE_USER',
    CHANGE_ROLE_USER: 'CHANGE_ROLE_USER',
}